services:
  frontend:
    image: react-express-mongodb-frontend
    ports:
      - 3000:3000

  backend:
    image: react-express-mongodb-backend
    depends_on:
      - mongo
    expose:
      - 3000
  
  mongo:
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    expose:
      - 27017
