apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      restartPolicy: Always
      containers:
      - image: {{ .Values.backend.image.name }}
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app: backend
